#!/bin/bash
set -e

# Ensure juypterlab build is fully up to date
jupyter lab build

# Update fonts
fc-cache -f -v

# Back to home
cd ~

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"
test -e test.png && rm test.png

# Set up OGGM paths
mkdir .oggm_cache
rm -f .oggm_config
echo "dl_cache_dir = $HOME/oggm_cache/download_cache" >> .oggm_config
echo "dl_cache_readonly = False" >> .oggm_config
echo "tmp_dir = $HOME/oggm_cache/tmp" >> .oggm_config
echo "rgi_dir = $HOME/oggm_cache/rgi" >> .oggm_config
echo "test_dir = $HOME/oggm_cache/OGGM_tests" >> .oggm_config
echo "has_internet = True" >> .oggm_config

# Pre-download oggm and salem sample-data
python binder/download_cache.py

# Make things pretty for users
cp binder/README_hub.md README.md
rm -rf binder
